### ISSUE TITLE
Angular data not binding in zf-tabs

### ISSUE THREAD

**Issue by mattgrande** [zurb/foundation-apps#588] opened 2015-04-17 13:25 UTC
I'm trying to dynamically create tabs. The titles are showing up correctly, but the content _within the tabs_ isn't being replaced with the proper data.

    <div zf-tabs="">
        <div ng-repeat="(key, data) in vm.feedTabs" zf-tab="" title="{{key}} -> {{data.length}}">
            Content for {{key}}. {{data.length}} tabs found.
        </div>
    </div>

The tab titles show up properly (eg, "Tab One -> 15"), however within the tab, the data shows up as "Content for .  tabs found."

**Comment by gjungb** [comment] 2015-04-17 18:19
@mattgrande this is due to the transclusion hell caused by the nesting of ```zf-tabs```, ```zf-tab``` and ```zf-tab-individual```. For a quick and dirty solution try this:
```Content for {{ $parent.key }}. {{ $parent.data.length }} tabs found.```

**Comment by mattgrande** [comment] 2015-04-20 13:02
Thanks, I'll try that out. For the time being, I decided to make my buttons look like tabs (which is probably a better idea in my case regardless).

**Comment by jeanieshark** [comment] 2015-05-01 23:25
For some of the other components, I've started adding in a way to "funnel" in your parent scope, and I'll look into doing this for tabs as well. Closing this issue for now.

**Closed by jeanieshark** 2015-05-01 23:25 UTC
Labels: bug, javascript

**Comment by vincentpalita** [comment] 2015-10-25 10:40
Hello there !
@jeanieshark : did you make any progress on this ?
I am using the zf-tabs and the way we access the parent scope can be disturbing.
Also, maybe I am wrong, but we cannot use the controllerAs alias inside a tab. That makes the whole thing really hard to track and to maintain.

Would love to hear from you about this.
Cheers,
Vincent

**Comment by zakdances** [comment] 2015-11-01 05:41
I'm not seeing any way in the [docs](http://foundation.zurb.com/apps/docs/#!/tabs) to access the parent scope. Has this been added yet?

**Comment by maman** [comment] 2016-01-20 05:06
still affected by this issue ... why this is issue is closed?

**Comment by makas2** [comment] 2016-03-19 11:59
Why it's close?
I have the same problem. And way use $parent daoesn't work any where.
angular ui-select component can't find model inside zf-tabs.

**Comment by paper-coffee** [comment] 2016-06-13 15:51
very poor design of zf-tabs!

**Comment by makas2** [comment] 2016-07-13 20:50
I have found solution.
First way we can set for every tab separeate controller.
The second way is to find scope for each tab item and set up data model.
To realaize second way firs of all you have to get DOM element of zf-tabs - angular.element(document.getElementbyId('zf-tabs element id'))
get child elements and getting scope() of them.
