### ISSUE TITLE
modal show/hide unstable

### ISSUE THREAD

**Issue by maxcook** [zurb/foundation-apps#402] opened 2015-01-13 14:40 UTC
If one opens and cloes a modal too fast it becomes unstable. Often closes instead of opens or opens but only shows the overlay, not the modal itself.

Can be tested on the docs page. Just open modal, close via overlay and open again (all quite fast)

**Comment by maxcook** [comment] 2015-01-15 16:09
Often if i open the same modal a second time, after a few seconds only the black overlay is visible, but the modal itself gets its class "is-active' removed and hides.

**Comment by toranaga** [comment] 2015-01-17 22:34
True. There is a problem. I noticed that import jquery breaks the modal window chrome, safari.
<script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="/assets/js/foundation.js"></script>

foundation.js ==>
'bower_components/fastclick/lib/fastclick.js',
'bower_components/viewport-units-buggyfill/viewport-units-buggyfill.js',
'bower_components/tether/tether.js',
'bower_components/angular/angular.js',
'bower_components/angular-animate/angular-animate.js',
'bower_components/ui-router/release/angular-ui-router.js',
'bower_components/foundation-apps/js/vendor/**/*.js',
'bower_components/foundation-apps/js/angular/**/*.js',
'!bower_components/foundation-apps/js/angular/app.js'

**Comment by maxcook** [comment] 2015-02-02 20:43
I am pretty sure that this is an issue with the animation settimeout. There should be an option in foundationapi to disable those animation

**Comment by joshuajohnson814** [comment] 2015-02-07 03:07
There is a similar issue with panel. Opening/closing fast causes issues where it randomly closes after opening.

**Comment by robotaoyuan** [comment] 2015-02-09 09:24
Does anyone have a good workaround for this bug?

**Comment by jeaniec** [comment] 2015-02-11 00:27
I think the latest commit https://github.com/zurb/foundation-apps/commit/e5a0580718c8ae12482c5f958e6df30c5ce5c982 should help with this bug. Marking it closed for now.

**Closed by jeaniec** 2015-02-11 00:27 UTC
Labels: bug, javascript

**Comment by toranaga** [comment] 2015-02-19 13:33
I checked with new version 1.0.3 still the same for chrome 40, safari.
JQuery import( <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>) before the foundation.js causes it.

**Comment by hal0gen** [comment] 2015-07-21 23:44
Same here, I am using 1.1.1 and I have to import jQuery before Foundation Apps, otherwise I'll break another plugin in my project (ngJcrop). Any ideas?

**Comment by hal0gen** [comment] 2015-07-22 10:32
I looked into it and got some more info on what happens, I think @maxcook was right. Reproduced the bug on both modal and panel: if jQuery is imported first, hovering the mouse on any element with a zf-toggle or zf-close fires an event which bubbles up to FoundationAnimation.animate and kills the modal/panel (disappears without animation and never opens again). A quick fix is to execute finishAnimation() only if timedOut is true, just like in setTimeout:

    //activate
    element[0].style.transitionDuration = '';
    element.addClass(activeClass);

    element.one(events.join(' '), function() {

        if (timedOut) {
            finishAnimation();
        }
    });

I don't know if this breaks some other functionality but apparently it works for me
